In [2]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [4]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True, dtype=int)
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [6]:
dataset.columns
dataset=dataset.drop("User ID",axis=1)

In [7]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [8]:
indep=dataset[["Age","EstimatedSalary","Gender_Male"]]
dep=dataset["Purchased"]

In [9]:
indep.shape

(400, 3)

In [10]:
dep

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [11]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [12]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

# 1. waht is the recall of (0)? ans => 1.00
#(or) what is the correct performance of non purches? ans => 1.00

# 2. waht is the recall of (1)? ans => 0.00 
#(or) what is the correct performance of  purches? ans => 0.00 

#3.what is the over all performance of accuracy?  ans => 0.63

#4.what is the performance of  precision (0) or non purches?  ans => 0.63
#5.what is the performance of  precision (1) or  purches?  ans => 0.00

#6.what is the performance of f1-score of (0)?  ans => 0.78
#7.what is the performance of f1-score of (1)?  ans => 0.00

#3.what is the macro avg of precision?  ans => 0.32
#3.what is the macro avg of recall?  ans => 0.50
#3.what is the macro avg of  f1-score?  ans => 0.39
#3.what is the weighted avg of precision?  ans => 0.40
#3.what is the weighted avg of recall?  ans => 0.63
#3.what is the weighted avg of f1-score?  ans => 0.43

              precision    recall  f1-score   support

           0       0.63      1.00      0.78        85
           1       0.00      0.00      0.00        49

    accuracy                           0.63       134
   macro avg       0.32      0.50      0.39       134
weighted avg       0.40      0.63      0.49       134

[[85  0]
 [49  0]]

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [13]:
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)
# 1. waht is the recall of (0)? ans => 1.00
#(or) what is the correct performance of non purches? ans => 1.00

# 2. waht is the recall of (1)? ans => 0.00 
#(or) what is the correct performance of  purches? ans => 0.00 

#3.what is the over all performance of accuracy?  ans => 0.63

#4.what is the performance of  precision (0) or non purches?  ans => 0.63
#5.what is the performance of  precision (1) or  purches?  ans => 0.00

#6.what is the performance of f1-score of (0)?  ans => 0.78
#7.what is the performance of f1-score of (1)?  ans => 0.00

#3.what is the macro avg of precision?  ans => 0.32
#3.what is the macro avg of recall?  ans => 0.50
#3.what is the macro avg of  f1-score?  ans => 0.39
#3.what is the weighted avg of precision?  ans => 0.40
#3.what is the weighted avg of recall?  ans => 0.63
#3.what is the weighted avg of f1-score?  ans => 0.43

              precision    recall  f1-score   support

           0       0.63      1.00      0.78        85
           1       0.00      0.00      0.00        49

    accuracy                           0.63       134
   macro avg       0.32      0.50      0.39       134
weighted avg       0.40      0.63      0.49       134

[[85  0]
 [49  0]]

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [14]:
from sklearn.naive_bayes import CategoricalNB
classifier =CategoricalNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

# 1. waht is the recall of (0)? ans => 0.96
#(or) what is the correct performance of non purches? ans =>  0.96

# 2. waht is the recall of (1)? ans => 0.63
#(or) what is the correct performance of  purches? ans => 0.63

#3.what is the over all performance of accuracy?  ans => 0.84

#4.what is the performance of  precision (0) or non purches?  ans => 0.82
#5.what is the performance of  precision (1) or  purches?  ans => 0.91

#6.what is the performance of f1-score of (0)?  ans => 0.89
#7.what is the performance of f1-score of (1)?  ans => 0.75

#3.what is the macro avg of precision?  ans => 0.87
#3.what is the macro avg of recall?  ans => 0.80
#3.what is the macro avg of  f1-score?  ans => 0.82
#3.what is the weighted avg of precision?  ans => 0.85
#3.what is the weighted avg of recall?  ans => 0.84
#3.what is the weighted avg of f1-score?  ans => 0.84

              precision    recall  f1-score   support

           0       0.82      0.96      0.89        85
           1       0.91      0.63      0.75        49

    accuracy                           0.84       134
   macro avg       0.87      0.80      0.82       134
weighted avg       0.85      0.84      0.84       134

[[82  3]
 [18 31]]

In [15]:
from sklearn.naive_bayes import ComplementNB
classifier =ComplementNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

# 1. waht is the recall of (0)? ans => 0.47
#(or) what is the correct performance of non purches? ans =>  0.47

# 2. waht is the recall of (1)? ans => 0.59
#(or) what is the correct performance of  purches? ans => 0.59

#3.what is the over all performance of accuracy?  ans => 0.51

#4.what is the performance of  precision (0) or non purches?  ans => 0.67
#5.what is the performance of  precision (1) or  purches?  ans => 0.39

#6.what is the performance of f1-score of (0)?  ans => 0.55
#7.what is the performance of f1-score of (1)?  ans => 0.47

#3.what is the macro avg of precision?  ans => 0.53
#3.what is the macro avg of recall?  ans => 0.53
#3.what is the macro avg of  f1-score?  ans => 0.51
#3.what is the weighted avg of precision?  ans => 0.57
#3.what is the weighted avg of recall?  ans => 0.51
#3.what is the weighted avg of f1-score?  ans => 0.52

              precision    recall  f1-score   support

           0       0.67      0.47      0.55        85
           1       0.39      0.59      0.47        49

    accuracy                           0.51       134
   macro avg       0.53      0.53      0.51       134
weighted avg       0.57      0.51      0.52       134

[[40 45]
 [20 29]]

In [ ]:
#logistic classification:
#========================


#3.what is the support of 0?  ans => 85
#3.what is the support of 1?  ans => 49
#3.what is the support of accuracy?  ans => 134
#3.what is the support of  macro avg?  ans => 134
#3.what is the support of weighted avg?  ans => 134