In [56]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [57]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [58]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [59]:
dataset=pd.get_dummies(dataset,drop_first=True, dtype=int)
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [60]:
dataset.columns
dataset=dataset.drop("User ID",axis=1)

In [61]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [62]:
indep=dataset[["Age","EstimatedSalary","Gender_Male"]]
dep=dataset["Purchased"]

In [63]:
indep.shape

(400, 3)

In [64]:
dep

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [65]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [67]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 2, metric = 'minkowski', p = 7)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=2, p=7)

In [69]:
y_pred = classifier.predict(X_test)

In [70]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [71]:
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)

In [73]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.77      0.92      0.84        85
           1       0.79      0.53      0.63        49

    accuracy                           0.78       134
   macro avg       0.78      0.72      0.74       134
weighted avg       0.78      0.78      0.76       134

In [54]:
print(cm)

[[78  7]
 [23 26]]

In [55]:
classifier.predict([[40,300,1,]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array([0], dtype=int64)

In [ ]:
#KNN classification:
#===================
# KNeighborsClassifier(n_neighbors = 2, metric = 'minkowski', p = 2)

# 1. waht is the recall of (0)? ans => 0.92
#(or) what is the correct performance of non purches? ans => 0.92

# 2. waht is the recall of (1)? ans => 0.53
#(or) what is the correct performance of  purches? ans => 0.53

#3.what is the over all performance of accuracy?  ans => 0.78

#4.what is the performance of  precision (0) or non purches?  ans => 0.77
#5.what is the performance of  precision (1) or  purches?  ans => 0.79

#6.what is the performance of f1-score of (0)?  ans => 0.84
#7.what is the performance of f1-score of (1)?  ans => 0.63

#3.what is the macro avg of precision?  ans => 0.78
#3.what is the macro avg of recall?  ans => 0.71
#3.what is the macro avg of  f1-score?  ans => 0.73
#3.what is the weighted avg of precision?  ans => 0.77
#3.what is the weighted avg of recall?  ans => 0.77
#3.what is the weighted avg of f1-score?  ans => 0.75

#3.what is the support of 0?  ans => 85
#3.what is the support of 1?  ans => 49
#3.what is the support of accuracy?  ans => 134
#3.what is the support of  macro avg?  ans => 134
#3.what is the support of weighted avg?  ans => 134


## KNeighborsClassifier(n_neighbors = 2, metric = 'minkowski', p = 7
#=========================================================================

# 1. waht is the recall of (0)? ans => 0.92
#(or) what is the correct performance of non purches? ans => 0.92

# 2. waht is the recall of (1)? ans => 0.53
#(or) what is the correct performance of  purches? ans => 0.53

#3.what is the over all performance of accuracy?  ans => 0.78

#4.what is the performance of  precision (0) or non purches?  ans => 0.77
#5.what is the performance of  precision (1) or  purches?  ans => 0.79

#6.what is the performance of f1-score of (0)?  ans => 0.84
#7.what is the performance of f1-score of (1)?  ans => 0.63

#3.what is the macro avg of precision?  ans => 0.78
#3.what is the macro avg of recall?  ans => 0.72
#3.what is the macro avg of  f1-score?  ans => 0.74
#3.what is the weighted avg of precision?  ans => 0.78
#3.what is the weighted avg of recall?  ans => 0.78
#3.what is the weighted avg of f1-score?  ans => 0.76

#3.what is the support of 0?  ans => 85
#3.what is the support of 1?  ans => 49
#3.what is the support of accuracy?  ans => 134
#3.what is the support of  macro avg?  ans => 134
#3.what is the support of weighted avg?  ans => 134